name: Deploy Worker
on:
  # repository_dispatch is necessary for the Cloudflare deploy button to work
  repository_dispatch:
  # Suggested branch config below if the project should be deployed on pushes to main
  # push:
  # branches:
  #   - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Prepare deploy
        run: |
          bun i
          bun run build
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --no-bundle
